# Change these first
owner: gymall # Your GitHub organization or username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: IServ Gymnasium Allermöhe
    url: https://gymall.de/iserv/
  - name: Moodle Gymnasium Allermöhe
    url: https://moodle.gymall.de/
  - name: Webseite Gymnasium Allermöhe
    url: https://gymnasium-allermoehe.hamburg.de/
  - name: eduPort Hamburg
    url: https://eduport.hamburg.de/
  - name: LMS Hamburg
    url: https://lms.lernen.hamburg/
#    __dangerous__body_degraded: "File not found"


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: upptime.it.gymall.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://moodle.gymall.de/pluginfile.php/1/core_admin/logo/0x200/1616999343/Mo%CC%88we%20farbig.png
  name: Upptime Monitor vom Gymnasium Allermöhe
  introTitle: "Status der Webseiten und Dienste vom Gymnasium Allermöhe"
  introMessage: Hier kann der Zustand von den einzelnen Webseiten und Diensten geprüft werden.
  navbar:
    - title: Status
      href: /upptime
    - title: IT Gymall
      href: https://it.gymall.de
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
