# Change these first
owner: gymall # Your GitHub organization or username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: IServ
    url: https://gymall.de/iserv/
    maxResponseTime: 1000
    icon: https://gymall.de/iserv/static/icons/favicon.ico
  - name: Moodle
    url: https://moodle.gymall.de/
    icon: https://moodle.gymall.de/theme/image.php/boost/theme/1616999343/favicon
  - name: Webseite
    url: https://gymnasium-allermoehe.hamburg.de/
    icon: https://gymnasium-allermoehe.hamburg.de/wp-content/uploads/sites/16/2018/02/cropped-GymAll-Icon-32x32.png
  - name: Digitale Kunstgalerie
    url: http://gymnasium-allermoehe.info/
    icon: https://gymnasium-allermoehe.hamburg.de/wp-content/uploads/sites/16/2018/02/cropped-GymAll-Icon-32x32.png
  - name: eduPort
    url: https://eduport.hamburg.de/
    maxResponseTime: 3000
    icon: https://eduport.hamburg.de/wp-content/uploads/sites/223/2016/04/cropped-icon-1-32x32.jpg
  - name: LMS
    url: https://lms.lernen.hamburg/
    maxResponseTime: 3000
    icon: https://lms.lernen.hamburg/theme/image.php/ocschool/theme/1616487992/favicon
#    expectedStatusCodes:
#      - 403
#    __dangerous__body_degraded: "File not found"

# CI schedule
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/10 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: upptime.it.gymall.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://moodle.gymall.de/pluginfile.php/1/core_admin/logo/0x200/1616999343/Mo%CC%88we%20farbig.png
  name: Gymnasium Allermöhe
  introTitle: "Status der Webseiten+Dienste des Gym Allermöhe"
  introMessage: Hier kann der Zustand von den einzelnen Webseiten und Diensten geprüft werden.
  navbar:
    - title: Status
      href: /upptime
    - title: IT Gymall
      href: https://it.gymall.de
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
